import json,csv,hashlib,re
from pathlib import Path
import numpy as np
import torch
from ase.io import read
ROOT=Path(__file__).resolve().parents[6];OUT=Path(__file__).resolve().parent;BASE=ROOT/'research/mace-v12-transfer/periodic_interface_v4';WB=OUT.parent;entry=BASE/'mace_periodic_v18_clean_core';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
ps=entry/'training_clean_core_01/selection_record.json';s=json.loads(ps.read_text());p18=entry/'evaluation_dev_01/evaluation.json';ev=json.loads(p18.read_text());ev17=json.loads((BASE/'mace_periodic_v17_interface_energy/evaluation_dev_01/evaluation.json').read_text());pins={str(p.relative_to(ROOT)):sha(p) for p in [ps,p18,WB/'v17_iteration_review/review.json',WB/'v17_frozen_dev_vector_diagnosis/per_atom.csv']}
for p,h in [(ROOT/s['model_path'],s['model_sha256']),(ROOT/s['recovery_verification']['checkpoint_path'],s['recovery_verification']['checkpoint_sha256']),(ROOT/s['training_stdout']['path'],s['training_stdout']['sha256']),(entry/'data/train.extxyz',s['training_input_sha256']),(entry/'data/dataset_manifest.json',s['dataset_manifest_sha256']),(entry/'data/valid.extxyz',s['development_validation_input_sha256'])]:assert sha(p)==h;pins[str(p.relative_to(ROOT))]=h
assert sha(ps)==ev['selection_record_sha256'] and s['model_sha256']==ev['model_sha256'];assert s['selected_epoch']==79 and s['completed_epochs']==80 and s['actual_cpu_threads']==4
# Artifact tensor identity only; no forward/force evaluation.
weights=torch.load(ROOT/s['recovery_verification']['checkpoint_path'],map_location='cpu',weights_only=False)['model'];exported=torch.load(ROOT/s['model_path'],map_location='cpu',weights_only=False).state_dict();assert weights.keys()==exported.keys() and all(torch.equal(weights[k],exported[k]) for k in weights);assert len(weights)==99
text=(ROOT/s['training_stdout']['path']).read_text();assert [int(x) for x in re.findall(r'INFO: Epoch (\d+):',text)]==list(range(80)) and 'INFO: Done' in text
m=json.loads((entry/'data/dataset_manifest.json').read_text());assert m['roles']['train']==30 and len(m['rows'])==30
csv18=list(csv.DictReader((entry/'evaluation_dev_01/per_atom.csv').open()));csv17=list(csv.DictReader((WB/'v17_frozen_dev_vector_diagnosis/per_atom.csv').open()));frames=read(entry/'data/valid.extxyz',':');metrics=[];spatial=[]
for a,x,y in zip(frames,ev17['per_structure'],ev['per_structure']):
 label=a.info['config_type'];assert x['label']==y['label']==label and x['reference_sha256']==y['reference_sha256'];ref=BASE/'pbe_interface_v17_main_targeted_acquisition/development_validation_archives'/label/(label+'_PW_PBE.extxyz');assert sha(ref)==y['reference_sha256'];pins[str(ref.relative_to(ROOT))]=sha(ref)
 for k in ['energy_abs_error_meV_atom','force_vector_RMSE_eV_A','force_vector_max_error_eV_A','separating_force_abs_error_eV_A']:metrics.append({'interface':x['interface'],'metric':k,'V17':x[k],'V18':y[k],'delta':y[k]-x[k]})
 rows17=[r for r in csv17 if r['label']==label];rows18=[r for r in csv18 if r['label']==label];assert len(rows17)==len(rows18)==len(a);assert all(int(r['id'])==int(t['lammps_id'])==int(a.arrays['lammps_id'][i]) for i,(r,t) in enumerate(zip(rows17,rows18)))
 e17=np.array([[float(r['error_'+d]) for d in 'xyz'] for r in rows17]);e18=np.array([[float(r['pred_f'+d])-float(r['ref_f'+d]) for d in 'xyz'] for r in rows18]);central=np.flatnonzero(a.arrays['central_pair']);i=next(k for k in central if a[k].symbol=='Ag');j=next(k for k in central if a[k].symbol!='Ag');axis=a.positions[j]-a.positions[i];axis/=np.linalg.norm(axis);dist=a.get_all_distances(mic=True);shell=np.minimum(dist[i],dist[j])<=4.5;sy=np.array(a.get_chemical_symbols());rms=lambda e:float(np.sqrt(np.mean(np.sum(e*e,axis=1))))
 item={'interface':x['interface'],'marked_ids':[int(a.arrays['lammps_id'][i]),int(a.arrays['lammps_id'][j])],'versions':{}}
 for version,e in [('V17',e17),('V18',e18)]:
  proj=e@axis;trans=e-proj[:,None]*axis;norm=np.linalg.norm(e,axis=1);k=int(np.argmax(norm));item['versions'][version]={'vector_RMSE':rms(e),'shell_RMSE':rms(e[shell]),'outside_RMSE':rms(e[~shell]),'longitudinal_RMS':float(np.sqrt(np.mean(proj**2))),'transverse_RMS':rms(trans),'Ag_pair_signed':float(proj[i]),'X_pair_signed':float(proj[j]),'separation_signed':float(proj[j]-proj[i]),'species_RMSE':{sp:rms(e[sy==sp]) for sp in set(sy)},'largest_atom_id':int(a.arrays['lammps_id'][k]),'largest_norm':float(norm[k])}
 assert abs(item['versions']['V18']['vector_RMSE']-y['force_vector_RMSE_eV_A'])<1e-10 and abs(abs(item['versions']['V18']['separation_signed'])-y['separating_force_abs_error_eV_A'])<1e-10
 spatial.append(item)
with (OUT/'matched_metrics.csv').open('w') as f:w=csv.DictWriter(f,fieldnames=list(metrics[0]));w.writeheader();w.writerows(metrics)
result={'source_hashes':pins,'model_checkpoint_tensor_identity':True,'tensor_count':99,'original_exit_receipt':'UNAVAILABLE','metrics':metrics,'spatial':spatial,'data_membership':'43->30; remove14 partial/add exactGamma frame0; not pure provenance ablation','no_inference':True};(OUT/'review.json').write_text(json.dumps(result,indent=2)+'\n')
lines=['# V9–V18 cumulative review: clean30 versus provisional43','','## Matched same-development results','|Interface|Vector V17 → V18|Separation V17 → V18|','|---|---|---|']
for x,y in zip(ev17['per_structure'],ev['per_structure']):lines.append(f"|{x['interface']}|{x['force_vector_RMSE_eV_A']:.6f} → {y['force_vector_RMSE_eV_A']:.6f}|{x['separating_force_abs_error_eV_A']:.6f} → {y['separating_force_abs_error_eV_A']:.6f}|")
lines+=['','AgC vector/max/separation worsen and loses its previous separation pass. AgSi vector/max and energy improve, but separation remains near0.19 and fails. AgTi aggregate/separation worsen slightly while maximum improves slightly. All vector gates fail; all separation gates fail; energies still pass. Clean provenance is beneficial bookkeeping, not automatic force accuracy.','']
for r in spatial:
 lines.append('### '+r['interface'])
 for version,v in r['versions'].items():lines.append(f"{version}: shell={v['shell_RMSE']:.6f}, outside={v['outside_RMSE']:.6f}, longitudinal={v['longitudinal_RMS']:.6f}, transverse={v['transverse_RMS']:.6f}, pairAg={v['Ag_pair_signed']:.6f}, pairX={v['X_pair_signed']:.6f}, pairdifference={v['separation_signed']:.6f} eV/A.")
lines+=['','## Completion and controlled comparison limits','Model/data/reference/selection hashes match. Independently checked all99 exported state tensors equal the frozen epoch79 checkpoint; no inference was run. Complete80-epoch/Done log exists, actual threads4. Original launcher exit receipt is unavailable: training_exit_code null is preserved, not replaced with inferred zero. Numerical epoch79 artifact identity does not recover historical process exit status.','Prior V9–V17 reviews remain valid with their comparable-set limitations. V18 changes43->30 membership by removing14 partial-source rows and adding exactGamma frame0. Coverage removal, reference distribution and mesh change are inseparable in this comparison; do not identify provenance as a sole cause. Defaults retain medium/seed45/batch1/lr1e-4/wd5e-7/80epochs/energy100/force1000 and fixed final79. Reused development references are not fresh validation.','','## Minimum evidence-driven V19 follow-up','A may review the six already-designed signed residual candidates, then authorize only those nonredundant acquisitions needed around AgC transverseTi and AgTi markedTi/frameworkC differential response, with AgSi pair differential as secondary coverage. Treat reused-development parents explicitly as acquisitions and freeze a fresh independent validation family before fitting. Hold recipe/checkpoint policy fixed and change only approved training labels in the next comparison; no weight/epoch changes justified by these observations alone. If no new label is authorized, report blocked coverage rather than lower gates.','Keep all current gates and sealed test labels outside training/choice. Contact screening and parent near-correlation require A review before assigning DFT owners. This recommendation is not an execution authorization, and no MD/TTM is supported.']
(OUT/'report.md').write_text('\n'.join(lines)+'\n');(OUT/'SHA256SUMS.txt').write_text(''.join(f'{sha(p)}  {p.name}\n' for p in sorted(OUT.iterdir()) if p.is_file() and p.name!='SHA256SUMS.txt'));print('V18 review hashes,99tensor identity,metrics and spatial checks PASS')
