import json,hashlib,subprocess,sys,importlib.util
from pathlib import Path
import numpy as np
from ase.io import read
ROOT=Path(__file__).resolve().parents[6];OUT=Path(__file__).resolve().parent;BASE=ROOT/'research/mace-v12-transfer/periodic_interface_v4';ENTRY=BASE/'mace_periodic_v19_residual_response';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
subprocess.run([sys.executable,str(ENTRY/'build_training_candidate.py'),'--check'],cwd=ROOT,check=True)
data=ENTRY/'training_candidate';m=json.loads((data/'manifest.json').read_text());a=read(data/'train.extxyz',':');assert m['roles']=={'train_candidate':36,'development_validation':0,'test':0} and len(a)==36 and m['composition_rank_exact']==4 and m['withheld_labels_opened'] is False and m['training_authorized'] is False
base=read(BASE/'mace_periodic_v18_clean_core/data/train.extxyz',':');assert len(base)==30
for i in range(30):assert np.array_equal(a[i].numbers,base[i].numbers) and np.array_equal(a[i].positions,base[i].positions) and np.array_equal(a[i].cell,base[i].cell) and np.array_equal(a[i].arrays['REF_forces'],base[i].arrays['REF_forces']) and a[i].info['REF_energy']==base[i].info['REF_energy']
for i,r in enumerate(m['new_rows'],30):
 assert r['frame_index']==i and r['lineage_role']=='training_acquisition_reused_development_family';assert np.isfinite(a[i].info['REF_energy']) and np.isfinite(a[i].arrays['REF_forces']).all();assert a[i].info['dataset_role']=='training_acquisition_reused_development_family'
assert len(m['new_rows'])==6 and len({r['config_type'] for r in m['new_rows']})==6
for rel,h in m['source_files_sha256'].items():assert sha(ROOT/rel)==h
pins={'train_candidate':sha(data/'train.extxyz'),'manifest':sha(data/'manifest.json'),'builder':sha(ENTRY/'build_training_candidate.py'),'preflight':sha(ENTRY/'preflight_v19.py'),'runner':sha(ENTRY/'run_v19_training.sh')}
result={'status':'TRAINING_CANDIDATE_INTEGRITY_PASS_OFFICIAL_ENTRY_BLOCKED','frames':36,'base30_exact_prefix':True,'new_labels':6,'exact_rank':4,'train_source_hashes':'PASS','dev_count':0,'test_count':0,'training_authorized':False,'fresh_dev_ready':False,'pins':pins,'limitations':m['limitations']}
(OUT/'audit.json').write_text(json.dumps(result,indent=2)+'\n');(OUT/'report.md').write_text('# V19 training36 candidate integrity audit\n\nThe read-only builder `--check` passes. The candidate preserves V18 clean30 as an exact 30-frame prefix and appends the six converged, verified V19 signed labels exactly once. All source hashes and finite label checks pass; exact composition rank4. All six new records retain the role `training_acquisition_reused_development_family`.\n\nThis is a **training candidate**, not an official training entry: manifest has dev0/test0 and training_authorized=false. Independent development geometry design is blocked because available V19 additions descend from the same three already-scored V17 development parent families. Do not train on this candidate until A supplies/fixes an independent development family and registers an entry review. The fixed V18 recipe remains unchanged, but this audit did not train or infer. Existing limitations include Gamma versus historical1x4x2 on frame0. No sealed labels or inputs were opened.\n');(OUT/'SHA256SUMS.txt').write_text(''.join(f'{sha(p)}  {p.name}\n' for p in sorted(OUT.iterdir()) if p.is_file() and p.name!='SHA256SUMS.txt'));print(result['status'])
