import json,hashlib,csv
from pathlib import Path
import numpy as np
from ase.io import read
ROOT=Path(__file__).resolve().parents[6];OUT=Path(__file__).resolve().parent;BASE=ROOT/'research/mace-v12-transfer/periodic_interface_v4/pbe_interface_v19_residual_acquisition';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();m=json.loads((BASE/'input_manifest.json').read_text());pairs=[];atoms=[];pins={str((BASE/'input_manifest.json').relative_to(ROOT)):sha(BASE/'input_manifest.json')}
for iface in ['AgC','AgSi','AgTi']:
 records=[r for r in m['records'] if r['label'].startswith(iface+'_')];assert len(records)==2;records.sort(key=lambda r:0 if '_m_' in r['label'] else 1);loaded=[]
 for r in records:
  src=BASE/r['input'];folder=BASE/'calculations'/r['label'];v=json.loads((folder/'verification.json').read_text());assert v['status']=='PASS' and all(v['checks'].values());assert sha(src)==r['input_sha256']
  for line in (folder/'SHA256SUMS.txt').read_text().splitlines():h,name=line.split(None,1);assert sha(folder/name)==h
  for p in [src,folder/'verification.json',folder/'summary.json',folder/'gpaw.log',folder/(r['label']+'_PW_PBE.extxyz')]:pins[str(p.relative_to(ROOT))]=sha(p)
  a=read(folder/(r['label']+'_PW_PBE.extxyz'));b=read(src);assert np.array_equal(a.positions,b.positions) and np.array_equal(a.arrays['lammps_id'],b.arrays['lammps_id']);s=json.loads((folder/'summary.json').read_text());loaded.append((a,s))
 minus,sm=loaded[0];plus,sp=loaded[1];assert sm['method']==sp['method'] and sm['energy_convention']==sp['energy_convention'];assert np.array_equal(minus.arrays['lammps_id'],plus.arrays['lammps_id']) and np.array_equal(minus.cell,plus.cell)
 delta=plus.positions-minus.positions;mag=np.linalg.norm(delta,axis=1);moved=mag>1e-8;dq=float(mag.max());assert dq>0;mode=delta/dq;fd=(plus.arrays['PW_PBE_forces']-minus.arrays['PW_PBE_forces'])/dq
 central=np.flatnonzero(plus.arrays['central_pair']);i=next(k for k in central if plus[k].symbol=='Ag');j=next(k for k in central if plus[k].symbol!='Ag');mid=(plus.positions+minus.positions)/2;axis=mid[j]-mid[i];axis/=np.linalg.norm(axis)
 signed={}
 for name,a in [('minus',minus),('plus',plus)]:
  f=a.arrays['PW_PBE_forces'];v=a.positions[j]-a.positions[i];v/=np.linalg.norm(v);signed[name]={'Ag':float(f[i]@v),'X':float(f[j]@v),'difference':float((f[j]-f[i])@v)}
 native=(sp['energy_eV_cell']-sm['energy_eV_cell'])/dq;free=(sp['free_energy_eV_cell']-sm['free_energy_eV_cell'])/dq;force_derivative=-float(np.sum((plus.arrays['PW_PBE_forces']+minus.arrays['PW_PBE_forces'])/2*mode));sy=np.array(plus.get_chemical_symbols());proj=fd@axis;trans=fd-proj[:,None]*axis;top=np.argsort(np.linalg.norm(fd,axis=1))[-5:][::-1]
 result={'interface':iface,'minus':records[0]['label'],'plus':records[1]['label'],'q_full_span_A':dq,'nominal_amplitude_A':dq/2,'moved_atom_ids':plus.arrays['lammps_id'][moved].tolist(),'moved_deltas_plus_minus_A':delta[moved].tolist(),'two_atom_relative_full_span_A':float(np.linalg.norm(delta[moved][0]-delta[moved][-1])) if moved.sum()==2 else None,'mode_normalization':'max moved-atom norm=1; derivatives per scalar mode q, not pair separation distance','energy_native_secant_eV_A':native,'energy_free_secant_eV_A':free,'negative_mean_force_dot_mode_eV_A':force_derivative,'native_force_residual':native-force_derivative,'free_force_residual':free-force_derivative,'pair_signed_force_eV_A':signed,'pair_response_difference_per_q':float((fd[j]-fd[i])@axis),'transverse_response_RMS':float(np.sqrt(np.mean(np.sum(trans**2,axis=1)))),'framework_response_RMS':float(np.sqrt(np.mean(np.sum(fd[sy!='Ag']**2,axis=1)))),'largest_response_ids':plus.arrays['lammps_id'][top].tolist(),'settings':sm['method'],'energy_convention':sm['energy_convention']};pairs.append(result)
 for k in range(len(plus)):
  row={'interface':iface,'id':int(plus.arrays['lammps_id'][k]),'species':plus[k].symbol,'moved':bool(moved[k]),'dforce_x_per_A':float(fd[k,0]),'dforce_y_per_A':float(fd[k,1]),'dforce_z_per_A':float(fd[k,2]),'longitudinal_response':float(proj[k]),'transverse_response':float(np.linalg.norm(trans[k]))};atoms.append(row)
with (OUT/'force_response.csv').open('w') as f:w=csv.DictWriter(f,fieldnames=list(atoms[0]));w.writeheader();w.writerows(atoms)
(OUT/'response.json').write_text(json.dumps({'pairs':pairs,'source_hashes':pins},indent=2)+'\n');lines=['# V19 signed DFT response review','','All six archives/hash manifests/input-output identity and exact signed-pair settings verified. q is normalized to maximum moved atom displacement; +/- q span0.12A forAgC and0.06A forAgSi/AgTi. Opposite two-atom modes have twice this relative moved-atom span. Force response CSV is dF/dq (eV/A²), not an inference/model error. Pair projections use each actual pair axis; response projection uses midpoint axis. These are reused-development-family acquisitions, not fresh independent validation.','']
for p in pairs:lines.append(p['interface']+': '+json.dumps({k:p[k] for k in ['q_full_span_A','moved_atom_ids','energy_native_secant_eV_A','energy_free_secant_eV_A','negative_mean_force_dot_mode_eV_A','pair_signed_force_eV_A','largest_response_ids']}))
lines+=['','## Integration recommendation','Retain all six verified signed diagnostics exactly once and their explicit source/development-family lineage; do not treat finite secants as missing-sign labels. Native/free-energy force-consistency residuals combine finite-displacement truncation and energy convention, so none establishes a wrong archive or sole model cause. Preserve native target and free energy separately. Review largest-response neighbors with prior V17/V18 residual diagnosis before further perturbations.','V19 training acquires derivatives of reused V17 development parents: those old parents cannot certify fresh generalization for this cycle. Require a distinct approved development family before entry passes isolation; if no independent labels exist mark blocked. Keep exact rank/source/method and unchanged recipe/gates. No new inference/DFT/MD/TTM, official data edits or sealed access.']
(OUT/'report.md').write_text('\n'.join(lines)+'\n');(OUT/'SHA256SUMS.txt').write_text(''.join(f'{sha(p)}  {p.name}\n' for p in sorted(OUT.iterdir()) if p.is_file() and p.name!='SHA256SUMS.txt'));print('six archives and three response pairs PASS')
